title: rahmad hidayat
email: rahmadhiidayat833@gmail.com
description: >
        This is my personal blog, Rahmad Hidayat. I come from North Aceh. I am currently a student at the State Polytechnic of Lhokseumawe, majoring in Information Technology and the study program of Computer Engineering. I am 19 years old now and my hobby is going to the gym.



url: "https://dayat-yat.github.io/dayatyat.github.io/"
plugins:
    -  jekyll-sitemap
    -  jekyll-feed
    -  jekyll-seo-tag